name: Retouch
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.14
  - pip=24.0
  - cudatoolkit=11.8
  - pytorch=2.3.1
  - torchvision=0.18.1
  - numpy=1.26.3
  - pip:
      - opencv-contrib-python==4.10.0.84
      - imageio==2.34.1
      - pytorch-lightning==1.6.5
      - omegaconf==2.3.0
      - einops==0.3.0
      - transformers==4.41.2
      - webdataset==0.2.100
      - kornia==0.7.4
      - open_clip_torch==2.0.2
      - invisible-watermark>=0.1.5
      - streamlit-drawable-canvas==0.8.0
      - torchmetrics==1.6.0
      - timm==0.6.7
      - prettytable==3.6.0
      - safetensors==0.4.3